CREATE TABLE [dbo].[CrewJoinDetails]
(
	[Id] UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	[CreatedDate] datetime2(7) NOT NULL DEFAULT GETUTCDATE(),
	[LastUpdatedDate] datetime2(7) NOT NULL DEFAULT GETUTCDATE(),
	[CrewJoinId] UNIQUEIDENTIFIER NOT NULL,
	[CrewId] UNIQUEIDENTIFIER NOT NULL,
	[Status] VARCHAR(255) NOT NULL DEFAULT 'PENDING'
)
